// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_req_connect.proto

#include "message_req_connect.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace message {
namespace protobuf {
class MessageReqConnectProtobufDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MessageReqConnectProtobuf> _instance;
} _MessageReqConnectProtobuf_default_instance_;
}  // namespace protobuf
}  // namespace message
static void InitDefaultsscc_info_MessageReqConnectProtobuf_message_5freq_5fconnect_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::message::protobuf::_MessageReqConnectProtobuf_default_instance_;
    new (ptr) ::message::protobuf::MessageReqConnectProtobuf();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::message::protobuf::MessageReqConnectProtobuf::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MessageReqConnectProtobuf_message_5freq_5fconnect_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MessageReqConnectProtobuf_message_5freq_5fconnect_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_message_5freq_5fconnect_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_message_5freq_5fconnect_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_message_5freq_5fconnect_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_message_5freq_5fconnect_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::message::protobuf::MessageReqConnectProtobuf, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::message::protobuf::MessageReqConnectProtobuf, orig_uri_),
  PROTOBUF_FIELD_OFFSET(::message::protobuf::MessageReqConnectProtobuf, dest_uri_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::message::protobuf::MessageReqConnectProtobuf)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::message::protobuf::_MessageReqConnectProtobuf_default_instance_),
};

const char descriptor_table_protodef_message_5freq_5fconnect_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031message_req_connect.proto\022\020message.pro"
  "tobuf\"\?\n\031MessageReqConnectProtobuf\022\020\n\010or"
  "ig_uri\030\001 \001(\t\022\020\n\010dest_uri\030\002 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_message_5freq_5fconnect_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_message_5freq_5fconnect_2eproto_sccs[1] = {
  &scc_info_MessageReqConnectProtobuf_message_5freq_5fconnect_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_message_5freq_5fconnect_2eproto_once;
static bool descriptor_table_message_5freq_5fconnect_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_5freq_5fconnect_2eproto = {
  &descriptor_table_message_5freq_5fconnect_2eproto_initialized, descriptor_table_protodef_message_5freq_5fconnect_2eproto, "message_req_connect.proto", 118,
  &descriptor_table_message_5freq_5fconnect_2eproto_once, descriptor_table_message_5freq_5fconnect_2eproto_sccs, descriptor_table_message_5freq_5fconnect_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_message_5freq_5fconnect_2eproto::offsets,
  file_level_metadata_message_5freq_5fconnect_2eproto, 1, file_level_enum_descriptors_message_5freq_5fconnect_2eproto, file_level_service_descriptors_message_5freq_5fconnect_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_message_5freq_5fconnect_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_message_5freq_5fconnect_2eproto), true);
namespace message {
namespace protobuf {

// ===================================================================

void MessageReqConnectProtobuf::InitAsDefaultInstance() {
}
class MessageReqConnectProtobuf::_Internal {
 public:
};

MessageReqConnectProtobuf::MessageReqConnectProtobuf()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:message.protobuf.MessageReqConnectProtobuf)
}
MessageReqConnectProtobuf::MessageReqConnectProtobuf(const MessageReqConnectProtobuf& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  orig_uri_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_orig_uri().empty()) {
    orig_uri_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.orig_uri_);
  }
  dest_uri_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_dest_uri().empty()) {
    dest_uri_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.dest_uri_);
  }
  // @@protoc_insertion_point(copy_constructor:message.protobuf.MessageReqConnectProtobuf)
}

void MessageReqConnectProtobuf::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MessageReqConnectProtobuf_message_5freq_5fconnect_2eproto.base);
  orig_uri_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dest_uri_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

MessageReqConnectProtobuf::~MessageReqConnectProtobuf() {
  // @@protoc_insertion_point(destructor:message.protobuf.MessageReqConnectProtobuf)
  SharedDtor();
}

void MessageReqConnectProtobuf::SharedDtor() {
  orig_uri_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dest_uri_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MessageReqConnectProtobuf::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MessageReqConnectProtobuf& MessageReqConnectProtobuf::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MessageReqConnectProtobuf_message_5freq_5fconnect_2eproto.base);
  return *internal_default_instance();
}


void MessageReqConnectProtobuf::Clear() {
// @@protoc_insertion_point(message_clear_start:message.protobuf.MessageReqConnectProtobuf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  orig_uri_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  dest_uri_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* MessageReqConnectProtobuf::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string orig_uri = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_orig_uri();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "message.protobuf.MessageReqConnectProtobuf.orig_uri"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string dest_uri = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_dest_uri();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "message.protobuf.MessageReqConnectProtobuf.dest_uri"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MessageReqConnectProtobuf::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:message.protobuf.MessageReqConnectProtobuf)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string orig_uri = 1;
  if (this->orig_uri().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_orig_uri().data(), static_cast<int>(this->_internal_orig_uri().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "message.protobuf.MessageReqConnectProtobuf.orig_uri");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_orig_uri(), target);
  }

  // string dest_uri = 2;
  if (this->dest_uri().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_dest_uri().data(), static_cast<int>(this->_internal_dest_uri().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "message.protobuf.MessageReqConnectProtobuf.dest_uri");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_dest_uri(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:message.protobuf.MessageReqConnectProtobuf)
  return target;
}

size_t MessageReqConnectProtobuf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:message.protobuf.MessageReqConnectProtobuf)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string orig_uri = 1;
  if (this->orig_uri().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_orig_uri());
  }

  // string dest_uri = 2;
  if (this->dest_uri().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_dest_uri());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MessageReqConnectProtobuf::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:message.protobuf.MessageReqConnectProtobuf)
  GOOGLE_DCHECK_NE(&from, this);
  const MessageReqConnectProtobuf* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MessageReqConnectProtobuf>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:message.protobuf.MessageReqConnectProtobuf)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:message.protobuf.MessageReqConnectProtobuf)
    MergeFrom(*source);
  }
}

void MessageReqConnectProtobuf::MergeFrom(const MessageReqConnectProtobuf& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:message.protobuf.MessageReqConnectProtobuf)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.orig_uri().size() > 0) {

    orig_uri_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.orig_uri_);
  }
  if (from.dest_uri().size() > 0) {

    dest_uri_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.dest_uri_);
  }
}

void MessageReqConnectProtobuf::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:message.protobuf.MessageReqConnectProtobuf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageReqConnectProtobuf::CopyFrom(const MessageReqConnectProtobuf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:message.protobuf.MessageReqConnectProtobuf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageReqConnectProtobuf::IsInitialized() const {
  return true;
}

void MessageReqConnectProtobuf::InternalSwap(MessageReqConnectProtobuf* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  orig_uri_.Swap(&other->orig_uri_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  dest_uri_.Swap(&other->dest_uri_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata MessageReqConnectProtobuf::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace message
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::message::protobuf::MessageReqConnectProtobuf* Arena::CreateMaybeMessage< ::message::protobuf::MessageReqConnectProtobuf >(Arena* arena) {
  return Arena::CreateInternal< ::message::protobuf::MessageReqConnectProtobuf >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
