# module makefile
# Auth: Ronghua Gao


OBJ_PATH := $(shell pwd)/../obj

BINS := com_test

com_test_SRC := comtest.cc
com_test_LDLIBS := -llog -lpub -lcom -pthread -lrt

LIBS := 
libpub_SRC := 

include $(PLATTOP)/super.mk
